project/NotaRestau/src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RestaurantRepository::class)]
class Restaurant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    #[ORM\Column(length: 255)]
    private ?string $phone_number = null;

    #[ORM\Column]
    private ?int $post_code = null;

    #[ORM\OneToMany(mappedBy: 'id_restaurant', targetEntity: UserReview::class)]
    private Collection $userReviews;

    #[ORM\ManyToOne(inversedBy: 'restaurants')]
    private ?User $id_user = null;

    public function __construct()
    {
        $this->userReviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getPostCode(): ?int
    {
        return $this->post_code;
    }

    public function setPostCode(int $post_code): self
    {
        $this->post_code = $post_code;

        return $this;
    }

    /**
     * @return Collection<int, UserReview>
     */
    public function getUserReviews(): Collection
    {
        return $this->userReviews;
    }

    public function addUserReview(UserReview $userReview): self
    {
        if (!$this->userReviews->contains($userReview)) {
            $this->userReviews->add($userReview);
            $userReview->setIdRestaurant($this);
        }

        return $this;
    }

    public function removeUserReview(UserReview $userReview): self
    {
        if ($this->userReviews->removeElement($userReview)) {
            // set the owning side to null (unless already changed)
            if ($userReview->getIdRestaurant() === $this) {
                $userReview->setIdRestaurant(null);
            }
        }

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }
}

project/NotaRestau/src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\Restaurant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('adress')
            ->add('phone_number')
            ->add('post_code')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

project/NotaRestau/src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Entity\User;
use App\Form\RestaurantType;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/restaurant')]
class RestaurantController extends AbstractController
{


    #[Route('/', name: 'app_restaurant_index', methods: ['GET'])]
    public function index(RestaurantRepository $restaurantRepository): Response
    {
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_restaurant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RestaurantRepository $restaurantRepository): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restaurantRepository->save($restaurant, true);

            return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form,
        ]);
    }

    #[Route('/{user}/list', name: 'app_restaurant_show', methods: ['GET'])]
    public function show(Restaurant $restaurant, RestaurantRepository $restaurantRepository, User $user): Response
    {
        $restaurants = $restaurantRepository->findBy(['id_user'=>$user->getId()]);
        dump($restaurants);
        return $this->render('restaurant/show.html.twig', [
            'restaurants' => $restaurants,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_restaurant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Restaurant $restaurant, RestaurantRepository $restaurantRepository): Response
    {
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restaurantRepository->save($restaurant, true);

            return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_restaurant_delete', methods: ['POST'])]
    public function delete(Request $request, Restaurant $restaurant, RestaurantRepository $restaurantRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $restaurant->getId(), $request->request->get('_token'))) {
            $restaurantRepository->remove($restaurant, true);
        }

        return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/show/user', name: 'app_restaurant_show', methods: ['GET'])]
    public function showByUser(RestaurantRepository $restaurantRepository): Response
    {
        $restaurants = [];
        if ($this->getUser() != null) {
            $restaurants = $restaurantRepository->findBy(['id_user' => $this->getUser()->getId()]);
        } else {
            $this->redirectToRoute('app_home');
        }

        return $this->render('restaurant/show.html.twig', [
            'restaurant' => $restaurants,
        ]);
    }
}

project/NotaRestau/templates/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('app_restaurant_delete', {'id': restaurant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.id) }}">
    <button class="btn">Delete</button>
</form>

project/NotaRestau/templates/restaurant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

project/NotaRestau/templates/restaurant/card.html.twig
<div class="card">
    <img src="{{ asset("build/images/card-img.jpg") }}" class=" card-img-top">
    <div class="card-body">
        <h5 class="card-title">{{ restaurant.name }}</h5>
        <p class="card-text">{{ restaurant.adress }}</p>
        <a href="#" class="btn btn-primary">Voir</a>
    </div>
</div>

project/NotaRestau/templates/restaurant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Restaurant{% endblock %}

{% block body %}
    <h1>Edit Restaurant</h1>

    {{ include('restaurant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_restaurant_index') }}">back to list</a>

    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}

project/NotaRestau/templates/restaurant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant index{% endblock %}

{% block body %}
    <h1>Restaurant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Adress</th>
                <th>Phone_number</th>
                <th>Post_code</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for restaurant in restaurants %}
            <tr>
                <td>{{ restaurant.id }}</td>
                <td>{{ restaurant.name }}</td>
                <td>{{ restaurant.adress }}</td>
                <td>{{ restaurant.phoneNumber }}</td>
                <td>{{ restaurant.postCode }}</td>
                <td>
                    <a href="{{ path('app_restaurant_show', {'id': restaurant.id}) }}">show</a>
                    <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_restaurant_new') }}">Create new</a>
{% endblock %}

project/NotaRestau/templates/restaurant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau restaurant{% endblock %}

{% block body %}
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1>Créer un nouveau restaurant</h1>

        {{ include('restaurant/_form.html.twig') }}

        <a href="{{ path('app_restaurant_index') }}">Retourner à vos restaurants</a>
    </div>
{% endblock %}

project/NotaRestau/templates/restaurant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block body %}
    <h1>Restaurants</h1>
    {% for restaurant in restaurant %}
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ restaurant.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ restaurant.name }}</td>
                </tr>
                <tr>
                    <th>Adress</th>
                    <td>{{ restaurant.adress }}</td>
                </tr>
                <tr>
                    <th>Phone_number</th>
                    <td>{{ restaurant.phoneNumber }}</td>
                </tr>
                <tr>
                    <th>Post_code</th>
                    <td>{{ restaurant.postCode }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>
        {{ include('restaurant/_delete_form.html.twig') }}

    {% endfor %}
    <a href="{{ path('app_restaurant_index') }}">back to list</a>
{% endblock %}